In [1]:
from gymnasium.envs.registration import register
import gymnasium as gym
from q_learn_code.agent.Agent import Agent
import numpy as np
import pandas as pd
from collections import defaultdict
from tqdm import tqdm

In [2]:
register(
     id="MARCPTR",
     entry_point="q_learn_code.envs:MARCPTR",
     max_episode_steps=300,
)

In [3]:
env = gym.make('q_learn_code.envs:MARCPTR')

In [4]:
env.define_user('89288865@N00')

In [5]:
env.reset()
env.render()
#env.set_size(25)

In [6]:
data = pd.read_csv("data_process/RawData/Perth/touristsVisits.csv")
startpoint = {}
for item in list(data['userID']):
    start = np.random.randint(25)
    end = start
    while (start == end):
        end = np.random.randint(25)
    startpoint[item] = (start, end)

In [7]:
done = False
observation, info = env.reset()
observation

{'agent': array([ 0, 12]), 'target': array([ 0, 24])}

In [8]:
acao = env.action_space.sample()
acao

14

In [9]:
proxima_observacao, _, done, _, _ = env.step(acao)

In [10]:
(proxima_observacao, done)

({'agent': array([ 0, 14]), 'target': array([ 0, 24])}, False)

In [25]:
a = np.zeros(shape=(4,4))
a[1, 2] = 10
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [27]:
np.max(a[1])

10.0

In [11]:
# hyperparameters
learning_rate = 0.01
n_episodes = 10000
start_epsilon = 1.0
epsilon_decay = start_epsilon / (n_episodes / 2)  # reduce the exploration over time
final_epsilon = 0.1
#################

agent = Agent(learning_rate=learning_rate,initial_epsilon=start_epsilon,
              epsilon_decay=epsilon_decay,final_epsilon=final_epsilon, q_table_size=25)

In [12]:
from collections import defaultdict
from tqdm import tqdm
import numpy as np
#env = gym.wrappers.RecordEpisodeStatistics(env, deque_size=n_episodes)
for episode in tqdm(range(n_episodes)):
    obs, info = env.reset()
    done = False

    # play one episode
    while not done:
        action = agent.get_action(obs['agent'], env)

        next_obs, reward, terminated, truncated, info = env.step(action)

        # update the agent
        agent.update(obs['agent'], action, reward, terminated, next_obs['agent'])

        # update if the environment is done and the current obs
        done = terminated or truncated

        obs = next_obs
    #print(reward)

    agent.decay_epsilon()

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:16<00:00, 609.76it/s]


In [13]:
agent.q_values
## delete enviroment
#gym.envs.registry
#del gym.envs.registry['MARCPTR']

array([[0.64506782, 0.82015609, 0.83155658, 0.67089313, 1.170937  ,
        0.61609531, 0.73412149, 0.8022319 , 0.5761573 , 0.59137144,
        1.22858834, 0.68905595, 0.85164274, 4.84386294, 0.9036095 ,
        0.52630246, 0.76384789, 0.80062024, 0.65591295, 0.77657961,
        0.82513942, 1.3254232 , 0.70285927, 0.91463029, 0.95018041],
       [4.35385034, 5.05216077, 4.84529085, 4.04291466, 5.21038784,
        4.52077957, 4.50983782, 4.42650664, 4.13938581, 3.86813022,
        5.34043871, 4.51492626, 4.45384271, 4.70992417, 4.27361736,
        3.56677645, 4.85377928, 4.36805195, 4.21342906, 3.995155  ,
        4.29926774, 5.01319098, 4.11072222, 5.05602265, 4.68730689],
       [2.34251525, 2.89699842, 2.7787242 , 2.11296491, 3.39148433,
        2.65917659, 2.52895001, 2.70880005, 2.37367854, 2.19585989,
        3.28776017, 2.85244849, 2.50564564, 2.75565869, 2.37123689,
        1.87967635, 2.88057707, 2.59931932, 2.37203009, 2.2266613 ,
        2.67469909, 3.4298165 , 2.27661698, 5.

In [ ]:
env.set_size(25)
env.get_size()

In [20]:
np.clip(np.matrix([0,4]) + np.matrix([1,4]), 0, 2)

matrix([[1, 2]])

In [17]:
np.matrix([0,2]) + np.matrix([1,0])

matrix([[1, 2]])

In [7]:
abs(25-15)


10

In [ ]:
import pickle as pk
file = open('data_process/adjacency', 'rb')
d = pk.load(file)
d

In [ ]:
import pickle as pk
file = open('data_process/adjacency', 'rb')
data = pk.load(file)
data

In [14]:
data['89288865@N00'][0,0]

-0.02869009230195615